[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.28.0"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "experimental" }

[dev]
  command = "npm run dev"
  port = 5173
